from tkinter import Tk, Button, Label, StringVar, Entry
from PIL import Image, ImageDraw, ImageFont
root = Tk()
root.score = 0
root.score2 = 0
root.score3 = 0
player1 = StringVar()
player2 = StringVar()
ends2 = StringVar()
#windows
#font = ImageFont.truetype("/path/to/font.ttf", 30)
#font = ImageFont.truetype(None, 30)
#font1 = ImageFont.truetype(None, 20)
#font2 = ImageFont.truetype(None, 25)
#linux
font = ImageFont.truetype("DejaVuSans.ttf", 30)
font1 = ImageFont.truetype("DejaVuSans.ttf", 20)
font2 = ImageFont.truetype("DejaVuSans.ttf", 25)
#apple
#font = ImageFont.truetype("Arial.ttf", 30)
#font1 = ImageFont.truetype("Arial.ttf", 20)
#font2 = ImageFont.truetype("Arial.ttf", 25)
root.geometry("300x250")
root.title("Lawn Bowls")
def save_info():
    player1_info = player1.get()
    player2_info = player2.get()
    file = open("text/scP1.txt", "w")
    file.write(player1_info)
    file = open("text/scP2.txt", "w")
    file.write(player2_info)
    file.close()
    img = Image.open("image/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((10, 12),(player1_info),(255,255,255),font=font2)
    draw.text((10, 61),(player2_info),(255,255,255),font=font2)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar2.png")
    img = Image.open("image/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((10, 47),(player1_info),(255,255,255),font=font2)
    draw.text((10, 95),(player2_info),(255,255,255),font=font2)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar5.png")
def clicked():
    root.score += 1
    L['text'] = ' ' + str(root.score)
    file = open("text/P1.txt", "w")
    file.write(str(root.score))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)   
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clicked2():
    root.score2 += 1
    K['text'] = ' ' + str(root.score2)
    file = open("P2.txt", "w")
    file.write(str(root.score2))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()        
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clicked3():
    root.score3 += 1
    J['text'] = ' ' + str(root.score3)
    file = open("E1.txt", "w")
    file.write(str(root.score3))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clicked4():
    root.score -= 1
    L['text'] = ' ' + str(root.score)
    file = open("text/P1.txt", "w")
    file.write(str(root.score))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clicked5():
    root.score2 -= 1
    K['text'] = ' ' + str(root.score2)
    file = open("text/P2.txt", "w")
    file.write(str(root.score2))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clicked6():
    root.score3 -= 1
    J['text'] = ' ' + str(root.score3)
    file = open("text/E1.txt", "w")
    file.write(str(root.score3))
    file.close()
    f = open("text/P1.txt", "r")
    if f.mode == 'r':
        F1 =f.read()
    g = open("text/P2.txt", "r")
    if g.mode == 'r':
        F2 =g.read()
    e = open("text/E1.txt", "r")
    if e.mode == 'r':
        F3 =e.read()
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
def clear():
    root.score = 0
    root.score2 = 0
    root.score3 = 0
    L['text'] = ' ' + str(root.score)
    K['text'] = ' ' + str(root.score2)
    J['text'] = ' ' + str(root.score3)
    player1_entry.delete(0, 'end')
    player2_entry.delete(0, 'end')
    with open("text/P1.txt", "w") as file:
        file.write(str(root.score))
    with open("text/P2.txt", "w") as file:
        file.write(str(root.score2))
    with open("text/E1.txt", "w") as file:
        file.write(str(root.score3))
    with open("text/P1.txt", "w") as f:
        f.write("")
    with open("text/P2.txt", "w") as g:
        g.write("")
    with open("text/E1.txt", "w") as e:
        e.write("")
    with open("text/P1.txt", "r") as f:
        F1 =f.read()
    with open("text/P2.txt", "r") as g:
        F2 =g.read()
    with open("text/E1.txt", "r") as e:
        F3 =e.read() 
    img = Image.open("image/scorebar2.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 8),(F1),(0,0,0),font=font)
    draw.text((250, 56),(F2),(0,0,0),font=font)
    draw = ImageDraw.Draw(img)
    draw.text((150, 105),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar3.png")
    img = Image.open("image/scorebar5.png")
    draw = ImageDraw.Draw(img)
    draw.text((250, 47),(F1),(0,0,0),font=font)
    draw.text((250, 92),(F2),(0,0,0),font=font)
    draw.text((150, 5),(F3),(255,255,255),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("image/scorebar6.png")
single = Label(root, text = "Scoreboard v2", font="Aria 12 bold").place(x = 90,y = 0)
name = Label(root, text = "Player 1", font="Aria 10 bold", fg="blue").place(x = 20, y = 40)
name1 = Label(root, text = "Player 2", font="Aria 10 bold", fg="red").place(x = 20, y = 80)
Home = Label(root, text = "Home", font="Aria 10 bold", fg="blue").place(x = 30, y = 120)
Away = Label(root, text = "Aways", font="Aria 10 bold", fg="green").place(x = 130, y = 120)
Ends = Label(root, text = "Ends", font="Aria 10 bold", fg="red").place(x = 230, y = 120)
L = Label(root, text = root.score, font="Aria 14 bold")
L.place(x = 30, y = 140)
K = Label(root, text = root.score2, font="Aria 14 bold")
K.place(x = 130, y = 140)
J = Label(root, text = root.score3, font="Aria 14 bold")
J.place(x = 230, y = 140)
player1_entry = Entry(root, textvariable = player1, width = "25")
player1_entry.place(x = 80, y = 40)
player2_entry = Entry(root, textvariable = player2, width = "25")
player2_entry.place(x = 80, y = 80)
btn1 = Button(root, text="Save", font="Aria 8 bold", relief="solid", command=save_info, fg="blue", bg="white").place(x = 240, y = 80)
b = Button(root, text="+", font="Aria 8 bold", relief="solid", command=clicked).place(x = 50, y = 170)
b2 = Button(root, text="+", font="Aria 8 bold", relief="solid", command=clicked2).place(x = 150, y = 170)
b3 = Button(root, text="+", font="Aria 8 bold", relief="solid", command=clicked3).place(x = 250, y = 170)
b4 = Button(root, text="-", font="Aria 8 bold", relief="solid", command=clicked4).place(x = 30, y = 170)
b5 = Button(root, text="-", font="Aria 8 bold", relief="solid", command=clicked5).place(x = 130, y = 170)
b6 = Button(root, text="-", font="Aria 8 bold", relief="solid", command=clicked6).place(x = 230, y = 170)
b1 = Button(root, text="Score Reset", font="Aria 8 bold", fg="blue", bg="white", relief="solid", command=clear).place(x = 110, y = 210)
root.wm_attributes("-topmost", 1)
root.resizable(0, 0)
root.mainloop()
