#!/usr/bin/python
from tkinter import Tk, Button, Label, StringVar, Entry, Frame, Canvas, NW, ttk
from PIL import ImageTk, Image, ImageDraw, ImageFont
from tkinter import colorchooser
import os
import configparser
import matplotlib.font_manager as fm
config = configparser.ConfigParser()
read_config = configparser.ConfigParser()
config1 = configparser.ConfigParser()
read_config1 = configparser.ConfigParser()
config2 = configparser.ConfigParser()
read_config2 = configparser.ConfigParser()
config3 = configparser.ConfigParser()
read_config3 = configparser.ConfigParser()
config4 = configparser.ConfigParser()
read_config4 = configparser.ConfigParser()
config5 = configparser.ConfigParser()
read_config5 = configparser.ConfigParser()
config6 = configparser.ConfigParser()
read_config6 = configparser.ConfigParser()
config7 = configparser.ConfigParser()
read_config7 = configparser.ConfigParser()
config8 = configparser.ConfigParser()
read_config8 = configparser.ConfigParser()
config9 = configparser.ConfigParser()
read_config9 = configparser.ConfigParser()
config10 = configparser.ConfigParser()
read_config10 = configparser.ConfigParser()
config11 = configparser.ConfigParser()
read_config11 = configparser.ConfigParser()
config12 = configparser.ConfigParser()
read_config12 = configparser.ConfigParser()
config13 = configparser.ConfigParser()
read_config13 = configparser.ConfigParser()
config14 = configparser.ConfigParser()
read_config14 = configparser.ConfigParser()
config15 = configparser.ConfigParser()
read_config15 = configparser.ConfigParser()
config16 = configparser.ConfigParser()
read_config16 = configparser.ConfigParser()
config17 = configparser.ConfigParser()
read_config17 = configparser.ConfigParser()
config18 = configparser.ConfigParser()
read_config18 = configparser.ConfigParser()
config19 = configparser.ConfigParser()
read_config19 = configparser.ConfigParser()
config20 = configparser.ConfigParser()
read_config20 = configparser.ConfigParser()
config21 = configparser.ConfigParser()
read_config21 = configparser.ConfigParser()
config22 = configparser.ConfigParser()
read_config22 = configparser.ConfigParser()
config23 = configparser.ConfigParser()
read_config23 = configparser.ConfigParser()
config24 = configparser.ConfigParser()
read_config24 = configparser.ConfigParser()
config30 = configparser.ConfigParser()
read_config30 = configparser.ConfigParser()
config31 = configparser.ConfigParser()
read_config31 = configparser.ConfigParser()
config32 = configparser.ConfigParser()
read_config32 = configparser.ConfigParser()
config33 = configparser.ConfigParser()
read_config33 = configparser.ConfigParser()
def raise_frame(frame):
    frame.tkraise()
root = Tk()
root.score = 0
root.score2 = 0
root.score3 = 0
root.score4 = 0
root.score5 = 0
player1 = StringVar()
player2 = StringVar()
n1 = StringVar()
n2 = StringVar()
n3 = StringVar()
n4 = StringVar()
n5 = StringVar()
n11 = StringVar()
v1 = StringVar()
v2 = StringVar()
Lea1 = StringVar()
Lea2 = StringVar()
Lea3 = StringVar()
Lea4 = StringVar()
Lea5 = StringVar()
Lea6 = StringVar()
Lea7 = StringVar()
Lea8 = StringVar()
Lea9 = StringVar()
Lea10 = StringVar()
Lea11 = StringVar()
Lea12 = StringVar()
Lea13 = StringVar()
Lea14 = StringVar()
Lea15 = StringVar()
Lea16 = StringVar()
Lea17 = StringVar()
Lea18 = StringVar()
Lea19 = StringVar()
Lea20 = StringVar()
Lea21 = StringVar()
Lea22 = StringVar()
Lea23 = StringVar()
Lea24 = StringVar()
Lea25 = StringVar()
Lea26 = StringVar()
Lea27 = StringVar()
Lea28 = StringVar()
Lea29 = StringVar()
Lea30 = StringVar()
Lea31 = StringVar()
Lea32 = StringVar()
Lea33 = StringVar()
Lea34 = StringVar()
f0 = Frame(root)
f1 = Frame(root)
f2 = Frame(root)
f3 = Frame(root)
f4 = Frame(root)
f5 = Frame(root)
root.geometry("350x260")
root.title("Lawn Bowls")
fonts = list(set([f.name for f in fm.fontManager.ttflist]))
fonts.sort()
combo = ttk.Combobox(f1, width = 20,value=fonts)
combo.place(x = 97, y = 30)
def clickee():
    config.set("Score", "1", fm.findfont(fm.FontProperties(family=combo.get())))
    with open('config/Config.ini', 'w') as configfile:
        config.write(configfile)       
def increase1():
     root.score4 += 1
     L1['text'] = ' ' + str(root.score4)
     config1.set("Score", "1", str(root.score4))
     with open('config/Config1.ini', 'w') as configfile:
         config1.write(configfile)
def decrease1():
     root.score4 -= 1
     L1['text'] = ' ' + str(root.score4)
     config1.set("Score", "1", str(root.score4))
     with open('config/Config1.ini', 'w') as configfile:
        config1.write(configfile)
def increase2():
     root.score5 += 1
     L2['text'] = ' ' + str(root.score5)
     config2.set("Score", "1", str(root.score5))
     with open('config/Config2.ini', 'w') as configfile:
         config2.write(configfile)
def decrease2():
     root.score5 -= 1
     L2['text'] = ' ' + str(root.score5)
     config2.set("Score", "1", str(root.score5))
     with open('config/Config2.ini', 'w') as configfile:
        config2.write(configfile)
def save():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 225, y = 125)
     n1 = color[1]
     config3.set("Score", "1", n1)
     with open('config/Config3.ini', 'w') as configfile:
        config3.write(configfile) 
def save2():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 225, y = 150)
     n2 = color[1]
     config4.set("Score", "1", n2)
     with open('config/Config4.ini', 'w') as configfile:
        config4.write(configfile)
def save3():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 225, y = 180)
     n3 = color[1]
     config5.set("Score", "1", n3)
     with open('config/Config5.ini', 'w') as configfile:
        config5.write(configfile)
def save4():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 225, y = 210)
     n4 = color[1]
     config6.set("Score", "1", n4)
     with open('config/Config6.ini', 'w') as configfile:
        config6.write(configfile)
        
def save5():
     config7.set("Score", "1", Lea1.get())
     config7.set("Score", "2", Lea2.get())
     with open('config/Config7.ini', 'w') as configfile:
        config7.write(configfile)
def save6():
     config8.set("Score", "1", Lea3.get())
     config8.set("Score", "2", Lea4.get())
     with open('config/Config8.ini', 'w') as configfile:
        config8.write(configfile)
def save7():
     config9.set("Score", "1", Lea5.get())
     config9.set("Score", "2", Lea6.get())
     with open('config/Config9.ini', 'w') as configfile:
        config9.write(configfile)
def save8():
     config10.set("Score", "1", Lea7.get())
     config10.set("Score", "2", Lea8.get())
     with open('config/Config10.ini', 'w') as configfile:
        config10.write(configfile)
def save9():
     config11.set("Score", "1", Lea9.get())
     config11.set("Score", "2", Lea10.get())
     with open('config/Config11.ini', 'w') as configfile:
        config11.write(configfile)
        
def save10():
     config12.set("Score", "1", Lea11.get())
     config12.set("Score", "2", Lea12.get())
     with open('config/Config12.ini', 'w') as configfile:
        config12.write(configfile)
def save11():
     config13.set("Score", "1", Lea13.get())
     config13.set("Score", "2", Lea14.get())
     with open('config/Config13.ini', 'w') as configfile:
        config13.write(configfile)
def save12():
     config14.set("Score", "1", Lea15.get())
     config14.set("Score", "2", Lea16.get())
     with open('config/Config14.ini', 'w') as configfile:
        config14.write(configfile)
def save13():
     config15.set("Score", "1", Lea17.get())
     config15.set("Score", "2", Lea18.get())
     with open('config/Config15.ini', 'w') as configfile:
        config15.write(configfile)        
def save14():
     config16.set("Score", "1", Lea19.get())
     config16.set("Score", "2", Lea20.get())
     with open('config/Config16.ini', 'w') as configfile:
        config16.write(configfile)           
def save15():
     config17.set("Score", "1", v1.get())
     with open('config/Config17.ini', 'w') as configfile:
        config17.write(configfile)
def save16():
     config18.set("Score", "1", Lea21.get())
     with open('config/Config18.ini', 'w') as configfile:
        config18.write(configfile)
def save17():
     config19.set("Score", "1", v2.get())
     with open('config/Config19.ini', 'w') as configfile:
        config19.write(configfile)
def save18():
     config20.set("Score", "1", Lea22.get())
     with open('config/Config20.ini', 'w') as configfile:
        config20.write(configfile)
def save19():
     config21.set("Score", "1", Lea23.get())
     config21.set("Score", "2", Lea24.get())
     with open('config/Config21.ini', 'w') as configfile:
        config21.write(configfile)
def save20():
     config22.set("Score", "1", Lea25.get())
     config22.set("Score", "2", Lea26.get())
     with open('config/Config22.ini', 'w') as configfile:
        config22.write(configfile)
def save21():
     config23.set("Score", "1", Lea27.get())
     config23.set("Score", "2", Lea28.get())
     with open('config/Config23.ini', 'w') as configfile:
        config23.write(configfile)       
def save22():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 205, y = 165)
     n5 = color[1]
     config24.set("Score", "1", n5)
     with open('config/Config24.ini', 'w') as configfile:
        config24.write(configfile)        
def save23():
     color = colorchooser.askcolor()
     label = Label(root, text="Colour", bg=color[1]).place(x = 205, y = 195)
     n11 = color[1]
     config30.set("Score", "1", n11)
     with open('config/Config30.ini', 'w') as configfile:
        config30.write(configfile)       
def save24():
     config31.set("Score", "1", Lea29.get())
     config31.set("Score", "2", Lea30.get())
     with open('config/Config31.ini', 'w') as configfile:
        config31.write(configfile)
     ends()
def save25():
     config32.set("Score", "1", Lea31.get())
     config32.set("Score", "2", Lea32.get())
     with open('config/Config32.ini', 'w') as configfile:
        config32.write(configfile)
     ends2()
def save26():
     config33.set("Score", "1", Lea33.get())
     config33.set("Score", "2", Lea34.get())
     with open('config/Config33.ini', 'w') as configfile:
        config33.write(configfile)
     ends3()    
def save_info():
    player1_info = player1.get()
    player2_info = player2.get()    
    file = open("scP1.txt", "w")
    file.write(player1_info)    
    file = open("scP2.txt", "w")
    file.write(player2_info)      
    file.close()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")    
    read_config7.read("config/Config7.ini")
    a = read_config7.get("Score", "1")
    b = read_config7.get("Score", "2")
    read_config8.read("config/Config8.ini")
    c = read_config8.get("Score", "1")
    d = read_config8.get("Score", "2")
    read_config12.read("config/Config12.ini")
    a1 = read_config12.get("Score", "1")
    b1 = read_config12.get("Score", "2")
    read_config13.read("config/Config13.ini")
    c1 = read_config13.get("Score", "1")
    d1 = read_config13.get("Score", "2")
    font = ImageFont.truetype(na,int(nb))
    img = Image.open("bars/scorebar.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),(player1_info),(nd),font=font)
    draw.text((int(c),int(d)),(player2_info),(ne),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar1.png")    
    img = Image.open("bars/scorebar3.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),(player1_info),(nd),font=font)
    draw.text((int(c),int(d)),(player2_info),(ne),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar4.png")    
    img = Image.open("bars/scorebar6.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a1),int(b1)),(player1_info),(nd),font=font)
    draw.text((int(c1),int(d1)),(player2_info),(ne),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar7.png")
    save4_info()                          
def save4_info():
    w1 = open("text/scP1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/scP2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")    
    read_config17.read("config/Config17.ini")
    a2 = read_config17.get("Score", "1")
    read_config18.read("config/Config18.ini")
    b2 = read_config18.get("Score", "1")
    read_config19.read("config/Config19.ini")
    c2 = read_config19.get("Score", "1")
    read_config20.read("config/Config20.ini")
    d2 = read_config20.get("Score", "1")    
    font = ImageFont.truetype(na,int(nb))    
    with Image.open('template/blank3.png') as img:
        width, height = img.size
        y = (int(width) - int(c2))
        img = Image.open("bars/score1a.png")
        draw = ImageDraw.Draw(img)
        draw.text((int(a2),int(b2)),(Z1),(nd),font=font)
        draw.text((int(y),int(d2)),(Z2),(ne),font=font)
        raw = ImageDraw.Draw(img)
        draw = ImageDraw.Draw(img)
        img.save("bars/score2a.png")   
def clicked():
    root.score += 1
    L['text'] = ' ' + str(root.score)
    file = open("text/P1.txt", "w")
    file.write(str(root.score))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def clicked2():
    root.score2 += 1
    K['text'] = ' ' + str(root.score2)
    file = open("text/P2.txt", "w")
    file.write(str(root.score2))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def clicked3():
    root.score3 += 1
    J['text'] = ' ' + str(root.score3)
    file = open("text/E1.txt", "w")
    file.write(str(root.score3))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def clicked4():
    root.score -= 1
    L['text'] = ' ' + str(root.score)
    file = open("text/P1.txt", "w")
    file.write(str(root.score))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def clicked5():
    root.score2 -= 1
    K['text'] = ' ' + str(root.score2)
    file = open("text/P2.txt", "w")
    file.write(str(root.score2))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def clicked6():
    root.score3 -= 1
    J['text'] = ' ' + str(root.score3)
    file = open("text/E1.txt", "w")
    file.write(str(root.score3))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")
def clear():
    root.score = 0
    root.score2 = 0
    root.score3 = 0
    L['text'] = ' ' + str(root.score)
    K['text'] = ' ' + str(root.score2)
    J['text'] = ' ' + str(root.score3)
    file = open("text/P1.txt", "w")
    file.write(str(root.score))
    file = open("text/P2.txt", "w")
    file.write(str(root.score2))    
    file = open("text/E1.txt", "w")
    file.write(str(root.score3))
    file.close()
    w1 = open("text/P1.txt", "r")
    if w1.mode == 'r':
        Z1 = w1.read()
    w2 = open("text/P2.txt", "r")
    if w2.mode == 'r':
        Z2 = w2.read()
    w3 = open("text/E1.txt", "r")
    if w3.mode == 'r':
        Z3 = w3.read()
    player1_info = player1.get()
    player2_info = player2.get()
    file = open("text/scP1.txt", "w")
    file.write(player1_info)
    file = open("text/scP2.txt", "w")
    file.write(player2_info)
    file.close()        
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")   
    read_config9.read("config/Config9.ini")    
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")    
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")    
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/scorebar1.png")
    draw = ImageDraw.Draw(img)   
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar2.png")
    img = Image.open("bars/scorebar4.png")
    draw = ImageDraw.Draw(img)    
    draw.text((int(e),int(f)),(Z1),(nf),font=font)
    draw.text((int(g),int(h)),(Z2),(ng),font=font)
    draw.text((int(i),int(j)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar5.png")
    img = Image.open("bars/scorebar7.png")
    draw = ImageDraw.Draw(img)    
    draw.text((int(e1),int(f1)),(Z1),(nf),font=font)
    draw.text((int(g1),int(h1)),(Z2),(ng),font=font)
    draw.text((int(i1),int(j1)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar8.png")
    img = Image.open("bars/score2a.png")
    draw = ImageDraw.Draw(img)    
    draw.text((int(e2),int(f2)),(Z1),(nf),font=font)
    draw.text((int(g2),int(h2)),(Z2),(ng),font=font)
    draw.text((int(i2),int(j2)),(Z3),(u7),font=font1)
    draw = ImageDraw.Draw(img)
    img.save("bars/score3a.png")    
def bac1():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")   
    read_config7.read("config/Config7.ini")
    a = read_config7.get("Score", "1")
    b = read_config7.get("Score", "2")
    read_config8.read("config/Config8.ini")
    c = read_config8.get("Score", "1")
    d = read_config8.get("Score", "2")
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")    
    font = ImageFont.truetype(na,int(nb))
    img = Image.open("template/blank.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),"Name 1",fill=(nd),font=font)
    draw.text((int(c),int(d)),"Name 2",fill=(ne),font=font)
    draw.text((int(e),int(f)),"01",fill=(nf),font=font)
    draw.text((int(g),int(h)),"02",fill=(ng),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("barrs/scorebar.png")
    img.show()
def bac2():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")   
    read_config7.read("config/Config7.ini")
    a = read_config7.get("Score", "1")
    b = read_config7.get("Score", "2")
    read_config8.read("config/Config8.ini")
    c = read_config8.get("Score", "1")
    d = read_config8.get("Score", "2")
    read_config9.read("config/Config9.ini")
    e = read_config9.get("Score", "1")
    f = read_config9.get("Score", "2")
    read_config10.read("config/Config10.ini")
    g = read_config10.get("Score", "1")
    h = read_config10.get("Score", "2")
    read_config11.read("config/Config11.ini")
    i = read_config11.get("Score", "1")
    j = read_config11.get("Score", "2")   
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1") 
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/1scorebar3.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),"Name 1",fill=(nd),font=font)
    draw.text((int(c),int(d)),"Name 2",fill=(ne),font=font)
    draw.text((int(e),int(f)),"01",fill=(nf),font=font)
    draw.text((int(g),int(h)),"02",fill=(ng),font=font)
    draw.text((int(i),int(j)),"03",fill=(u7),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("barrs/scorebar3.png")
    img.show()
def bac3():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config12.read("config/Config12.ini")
    a1 = read_config12.get("Score", "1")
    b1 = read_config12.get("Score", "2")
    read_config13.read("config/Config13.ini")
    c1 = read_config13.get("Score", "1")
    d1 = read_config13.get("Score", "2")
    read_config14.read("config/Config14.ini")
    e1 = read_config14.get("Score", "1")
    f1 = read_config14.get("Score", "2")
    read_config15.read("config/Config15.ini")
    g1 = read_config15.get("Score", "1")
    h1 = read_config15.get("Score", "2")
    read_config16.read("config/Config16.ini")
    i1 = read_config16.get("Score", "1")
    j1 = read_config16.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1") 
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    img = Image.open("bars/1scorebar6.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a1),int(b1)),"Name 1",fill=(nd),font=font)
    draw.text((int(c1),int(d1)),"Name 2",fill=(ne),font=font)
    draw.text((int(e1),int(f1)),"01",fill=(nf),font=font)
    draw.text((int(g1),int(h1)),"02",fill=(ng),font=font)
    draw.text((int(i1),int(j1)),"03",fill=(u7),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("barrs/1scorebar6.png")
    img.show()
def bac4():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config1.read("config/Config1.ini")
    nb = read_config1.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")
    read_config3.read("config/Config3.ini")
    nd = read_config3.get("Score", "1")
    read_config4.read("config/Config4.ini")
    ne = read_config4.get("Score", "1")    
    read_config5.read("config/Config5.ini")
    nf = read_config5.get("Score", "1")
    read_config6.read("config/Config6.ini")
    ng = read_config6.get("Score", "1")    
    read_config17.read("config/Config17.ini")
    a2 = read_config17.get("Score", "1")
    read_config18.read("config/Config18.ini")
    b2 = read_config18.get("Score", "1")
    read_config19.read("config/Config19.ini")
    c2 = read_config19.get("Score", "1")
    read_config20.read("config/Config20.ini")
    d2 = read_config20.get("Score", "1")
    read_config21.read("config/Config21.ini")
    e2 = read_config21.get("Score", "1")
    f2 = read_config21.get("Score", "2")
    read_config22.read("config/Config22.ini")
    g2 = read_config22.get("Score", "1")
    h2 = read_config22.get("Score", "2")
    read_config23.read("config/Config23.ini")
    i2 = read_config23.get("Score", "1")
    j2 = read_config23.get("Score", "2")   
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1") 
    font = ImageFont.truetype(na,int(nb))
    font1 = ImageFont.truetype(na,int(nc))
    with Image.open('template/blank3.png') as img:
        width, height = img.size
        y = (int(width) - int(c2))
    img = Image.open("bars/1score1a.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a2),int(b2)),"Name 1",fill=(nd),font=font)
    draw.text((int(y),int(d2)),"Name 2",fill=(ne),font=font)
    draw.text((int(e2),int(f2)),"01",fill=(nf),font=font)
    draw.text((int(g2),int(h2)),"02",fill=(ng),font=font)
    draw.text((int(i2),int(j2)),"03",fill=(u7),font=font1)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("barrs/1score1a.png")
    img.show()
def ends():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")  
    read_config32.read("config/Config31.ini")
    a = read_config31.get("Score", "1")
    b = read_config31.get("Score", "2")
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1") 
    font = ImageFont.truetype(na,int(nc))
    img = Image.open("template/blank1.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),"Ends:",fill=(u7),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar3.png")
    img.show()
def ends2():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")  
    read_config32.read("config/Config32.ini")
    a = read_config32.get("Score", "1")
    b = read_config32.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1") 
    font = ImageFont.truetype(na,int(nc))
    img = Image.open("template/blank2.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),"Ends:",fill=(u7),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/scorebar6.png")
    img.show()
def ends3():
    read_config.read("config/Config.ini")
    na = read_config.get("Score", "1")
    read_config2.read("config/Config2.ini")
    nc = read_config2.get("Score", "1")  
    read_config33.read("config/Config33.ini")
    a = read_config33.get("Score", "1")
    b = read_config33.get("Score", "2")    
    read_config30.read("config/Config30.ini")
    u7 = read_config30.get("Score", "1")   
    font = ImageFont.truetype(na,int(nc))
    img = Image.open("template/blank3.png")
    draw = ImageDraw.Draw(img)
    draw.text((int(a),int(b)),"Ends:",fill=(u7),font=font)
    raw = ImageDraw.Draw(img)
    draw = ImageDraw.Draw(img)
    img.save("bars/score1a.png")
    img.show()    
config.add_section("Score")
config1.add_section("Score")
config2.add_section("Score")
config3.add_section("Score")
config4.add_section("Score")
config5.add_section("Score")
config6.add_section("Score")
config7.add_section("Score")
config8.add_section("Score")
config9.add_section("Score")
config10.add_section("Score")
config11.add_section("Score")
config12.add_section("Score")
config13.add_section("Score")
config14.add_section("Score")
config15.add_section("Score")
config16.add_section("Score")
config17.add_section("Score")
config18.add_section("Score")
config19.add_section("Score")
config20.add_section("Score")
config21.add_section("Score")
config22.add_section("Score")
config23.add_section("Score")
config24.add_section("Score")
config30.add_section("Score")
config31.add_section("Score")
config32.add_section("Score")
config33.add_section("Score")
cs1 = Canvas(f3, width = 220, height = 80)
cs1.place(x = 110, y = 10)
img1 = ImageTk.PhotoImage(Image.open("image/s1.png"))
cs1.create_image(0, 0, anchor=NW, image=img1)
cs2 = Canvas(f4, width = 220, height = 80)
cs2.place(x = 120, y = 10)
img2 = ImageTk.PhotoImage(Image.open("image/s3.png"))
cs2.create_image(0, 0, anchor=NW, image=img2)
cs3 = Canvas(f5, width = 240, height = 80)
cs3.place(x = 70, y = 40)
img3 = ImageTk.PhotoImage(Image.open("image/s5.png"))
cs3.create_image(0, 0, anchor=NW, image=img3)
cs4 = Canvas(f2, width = 240, height = 80)
cs4.place(x = 130, y = 37)
img4 = ImageTk.PhotoImage(Image.open("image/s2.png"))
cs4.create_image(0, 0, anchor=NW, image=img4)
for frame in (f0, f1, f2, f3, f4, f5):
    frame.place(x = 0,y = 0, width=350, height=310)    
Label(f0, text = "Scoreboard V2 L", font="Aria 12 bold").place(x = 100,y = 0)
Label(f0, text = "Player 1", font="Aria 10 bold", fg="blue").place(x = 10, y = 28)
Label(f0, text = "Player 2", font="Aria 10 bold", fg="blue").place(x = 10, y = 59)
Label(f0, text = "Home", font="Aria 10 bold", fg="blue").place(x = 50, y = 120)
Label(f0, text = "Aways", font="Aria 10 bold", fg="green").place(x = 150, y = 120)
Label(f0, text = "Ends", font="Aria 10 bold", fg="red").place(x = 250, y = 120)
Label(f0, text = "N1", font="Aria 10 bold", fg="red").place(x = 205, y = 30)
Label(f0, text = "N2", font="Aria 10 bold", fg="red").place(x = 205, y = 60)
L = Label(f0, text = root.score, font="Aria 14 bold")
L.place(x = 50, y = 140)
K = Label(f0, text = root.score2, font="Aria 14 bold")
K.place(x = 150, y = 140)
J = Label(f0, text = root.score3, font="Aria 14 bold")
J.place(x = 250, y = 140)
Entry(f0, textvariable = player1, width = "15", relief="solid").place(x = 80, y = 30)
Entry(f0, textvariable = player2, width = "15", relief="solid").place(x = 80, y = 60)
Entry(f0, textvariable = v1, width = "5", relief="solid").place(x = 230, y = 30)
Entry(f0, textvariable = v2, width = "5", relief="solid").place(x = 230, y = 60)
Button(f0, text="---Save---", font="Aria 8 bold", relief="solid", command=save_info, fg="blue", bg="white").place(x = 125, y = 90)
Button(f0, text="Save", font="Aria 8 bold", relief="solid", command=save18, fg="red", bg="white").place(x = 280, y = 25)
Button(f0, text="Save", font="Aria 8 bold", relief="solid", command=save20, fg="red", bg="white").place(x = 280, y = 60)
Button(f0, text="+", font="Aria 8 bold", relief="solid", command=clicked).place(x = 75, y = 170)
Button(f0, text="+", font="Aria 8 bold", relief="solid", command=clicked2).place(x = 175, y = 170)
Button(f0, text="+", font="Aria 8 bold", relief="solid", command=clicked3).place(x = 275, y = 170)
Button(f0, text="-", font="Aria 8 bold", relief="solid", command=clicked4).place(x = 40, y = 170)
Button(f0, text="-", font="Aria 8 bold", relief="solid", command=clicked5).place(x = 140, y = 170)
Button(f0, text="-", font="Aria 8 bold", relief="solid", command=clicked6).place(x = 240, y = 170)
Button(f0, text="Score Reset", font="Aria 8 bold", fg="blue", bg="white", relief="solid", command=clear).place(x = 130, y = 210)
Label(f1, text = "Font truetype", font = "none 8 bold").place(x = 5,y = 30)
Button(f1, text="Select", command=clickee, fg="blue", bg="white", relief="solid").place(x = 277, y = 30)
Label(f1, text = "Scorebar Customizer", font="none 12 bold").place(x = 70,y = 5)
Label(f1, text = "Name Size", font="none 8 bold").place(x = 5,y = 60)
Label(f1, text = "End Size", font="none 8 bold").place(x = 5,y = 90)
Label(f1, text = "Name1 Colour", font="none 8 bold").place(x = 5,y = 125)
Label(f1, text = "Name2 Colour", font="none 8 bold").place(x = 5,y = 155)
Label(f1, text = "S01 Colour", font="none 8 bold").place(x = 5,y = 185)
Label(f1, text = "S02 Colour", font="none 8 bold").place(x = 5,y = 215)
Label(f3, text = "Bar 1&2", font="none 14 bold").place(x = 5,y = 20)
Label(f3, text = "Pos Name1", font="none 8 bold").place(x = 5,y = 70)
Label(f3, text = "Pos Name2", font="none 8 bold").place(x = 5,y = 100)
Label(f3, text = "Pos Score1", font="none 8 bold").place(x = 5,y = 130)
Label(f3, text = "Pos Score2", font="none 8 bold").place(x = 5,y = 160)
Label(f3, text = "Pos EScore", font="none 8 bold").place(x = 5,y = 190)
Label(f4, text = "Bar 3", font="none 14 bold").place(x = 5,y = 20)
Label(f4, text = "Pos Name1", font="none 8 bold").place(x = 5,y = 70)
Label(f4, text = "Pos Name2", font="none 8 bold").place(x = 5,y = 100)
Label(f4, text = "Pos Score1", font="none 8 bold").place(x = 5,y = 130)
Label(f4, text = "Pos Score2", font="none 8 bold").place(x = 5,y = 160)
Label(f4, text = "Pos EScore", font="none 8 bold").place(x = 5,y = 190)
Label(f5, text = "Bar 4", font="none 14 bold").place(x = 130,y = 10)
Label(f5, text = "Pos Name1", font="none 8 bold").place(x = 5,y = 70)
Label(f5, text = "Pos Name2", font="none 8 bold").place(x = 5,y = 100)
Label(f5, text = "Pos Score1", font="none 8 bold").place(x = 5,y = 130)
Label(f5, text = "Pos Score2", font="none 8 bold").place(x = 5,y = 160)
Label(f5, text = "Pos EScore", font="none 8 bold").place(x = 5,y = 190)
Button(f1, text="Decrease", width=7,command=decrease1, fg="blue", bg="white", relief="solid").place(x = 95, y = 60)
Button(f1, text="Increase", width=7,command=increase1, fg="blue", bg="white", relief="solid").place(x = 185, y = 60)
Button(f1, text="Decrease", width=7,command=decrease2, fg="blue", bg="white", relief="solid").place(x = 95, y = 90)
Button(f1, text="Increase", width=7,command=increase2, fg="blue", bg="white", relief="solid").place(x = 185, y = 90)
Button(f1, text="Choose Colour", command=save, fg="blue", bg="white", relief="solid").place(x = 95, y = 120)
Button(f1, text="Choose Colour", command=save2, fg="blue", bg="white", relief="solid").place(x = 95, y = 150)
Button(f1, text="Choose Colour", command=save3, fg="blue", bg="white", relief="solid").place(x = 95, y = 180)
Button(f1, text="Choose Colour", command=save4, fg="blue", bg="white", relief="solid").place(x = 95, y = 210)
L1 = Label(f1, text = root.score4, font="Aria 14 bold")
L1.place(x = 280, y = 60)
L2 = Label(f1, text = root.score5, font="Aria 14 bold")
L2.place(x = 280, y = 90)
Label(f2, text = "Position Ends:", font="none 12 bold", fg="blue").place(x = 120,y = 15)
Label(f2, text = "Ends: Bar2", font="none 8 bold", fg="blue").place(x = 5,y = 75)
Entry(f2, textvariable = Lea29, width = "10", relief="solid").place(x = 90, y = 70)
Entry(f2, textvariable = Lea30, width = "10", relief="solid").place(x = 185, y = 70)
Label(f2, text = "Ends: Bar3", font="none 8 bold", fg="blue").place(x = 5,y = 105)
Entry(f2, textvariable = Lea31, width = "10", relief="solid").place(x = 90, y = 100)
Entry(f2, textvariable = Lea32, width = "10", relief="solid").place(x = 185, y = 100)
Label(f2, text = "Ends: Bar4", font="none 8 bold", fg="blue").place(x = 5,y = 135)
Entry(f2, textvariable = Lea33, width = "10", relief="solid").place(x = 90, y = 130)
Entry(f2, textvariable = Lea34, width = "10", relief="solid").place(x = 185, y = 130)
Label(f2, text = "N03 Colour", font="none 8 bold", fg="blue").place(x = 5,y = 165)
Label(f2, text = "Ends: Colour", font="none 8 bold", fg="blue").place(x = 5,y = 195)
Button(f2, text="Ends", command=save24, fg="blue", bg="white", relief="solid").place(x = 280, y = 70)
Button(f2, text="Ends", command=save25, fg="blue", bg="white", relief="solid").place(x = 280, y = 100)
Button(f2, text="Ends", command=save26, fg="blue", bg="white", relief="solid").place(x = 280, y = 130)
Button(f2, text="Choose Colour", command=save22, fg="blue", bg="white", relief="solid").place(x = 90, y = 160)
Button(f2, text="Choose Colour", command=save23, fg="blue", bg="white", relief="solid").place(x = 90, y = 190)
Entry(f3, textvariable = Lea1, width = "10", relief="solid").place(x = 85, y = 70)
Entry(f3, textvariable = Lea2, width = "10", relief="solid").place(x = 185, y = 70)
Entry(f3, textvariable = Lea3, width = "10", relief="solid").place(x = 85, y = 100)
Entry(f3, textvariable = Lea4, width = "10", relief="solid").place(x = 185, y = 100)
Entry(f3, textvariable = Lea5, width = "10", relief="solid").place(x = 85, y = 130)
Entry(f3, textvariable = Lea6, width = "10", relief="solid").place(x = 185, y = 130)
Entry(f3, textvariable = Lea7, width = "10", relief="solid").place(x = 85, y = 160)
Entry(f3, textvariable = Lea8, width = "10", relief="solid").place(x = 185, y = 160)
Entry(f3, textvariable = Lea9, width = "10", relief="solid").place(x = 85, y = 190)
Entry(f3, textvariable = Lea10, width = "10", relief="solid").place(x = 185, y = 190)
Button(f3, text="Save", command=save5, fg="blue", bg="white", relief="solid").place(x = 280, y = 70)
Button(f3, text="Save", command=save6, fg="blue", bg="white", relief="solid").place(x = 280, y = 100)
Button(f3, text="Save", command=save7, fg="blue", bg="white", relief="solid").place(x = 280, y = 130)
Button(f3, text="Save", command=save8, fg="blue", bg="white", relief="solid").place(x = 280, y = 160)
Button(f3, text="Save", command=save9, fg="blue", bg="white", relief="solid").place(x = 280, y = 190)
Entry(f4, textvariable = Lea11, width = "10", relief="solid").place(x = 85, y = 70)
Entry(f4, textvariable = Lea12, width = "10", relief="solid").place(x = 185, y = 70)
Entry(f4, textvariable = Lea13, width = "10", relief="solid").place(x = 85, y = 100)
Entry(f4, textvariable = Lea14, width = "10", relief="solid").place(x = 185, y = 100)
Entry(f4, textvariable = Lea15, width = "10", relief="solid").place(x = 85, y = 130)
Entry(f4, textvariable = Lea16, width = "10", relief="solid").place(x = 185, y = 130)
Entry(f4, textvariable = Lea17, width = "10", relief="solid").place(x = 85, y = 160)
Entry(f4, textvariable = Lea18, width = "10", relief="solid").place(x = 185, y = 160)
Entry(f4, textvariable = Lea19, width = "10", relief="solid").place(x = 85, y = 190)
Entry(f4, textvariable = Lea20, width = "10", relief="solid").place(x = 185, y = 190)
Button(f4, text="Save", command=save10, fg="blue", bg="white", relief="solid").place(x = 280, y = 70)
Button(f4, text="Save", command=save11, fg="blue", bg="white", relief="solid").place(x = 280, y = 100)
Button(f4, text="Save", command=save12, fg="blue", bg="white", relief="solid").place(x = 280, y = 130)
Button(f4, text="Save", command=save13, fg="blue", bg="white", relief="solid").place(x = 280, y = 160)
Button(f4, text="Save", command=save14, fg="blue", bg="white", relief="solid").place(x = 280, y = 190)
Entry(f5, textvariable = v1, width = "7", relief="solid").place(x = 80, y = 70)
Entry(f5, textvariable = Lea21, width = "7", relief="solid").place(x = 209, y = 70)
Entry(f5, textvariable = v2, width = "7", relief="solid").place(x = 80, y = 100)
Entry(f5, textvariable = Lea22, width = "7", relief="solid").place(x = 209, y = 100)
Entry(f5, textvariable = Lea23, width = "10", relief="solid").place(x = 80, y = 130)
Entry(f5, textvariable = Lea24, width = "10", relief="solid").place(x = 182, y = 130)
Entry(f5, textvariable = Lea25, width = "10", relief="solid").place(x = 80, y = 160)
Entry(f5, textvariable = Lea26, width = "10", relief="solid").place(x = 182, y = 160)
Entry(f5, textvariable = Lea27, width = "10", relief="solid").place(x = 80, y = 190)
Entry(f5, textvariable = Lea28, width = "10", relief="solid").place(x = 182, y = 190)
Button(f5, text="Save", command=save15, fg="blue", bg="white", relief="solid").place(x = 145, y = 70)
Button(f5, text="Save", command=save16, fg="blue", bg="white", relief="solid").place(x = 280, y = 70)
Button(f5, text="Save", command=save17, fg="blue", bg="white", relief="solid").place(x = 145, y = 100)
Button(f5, text="Save", command=save18, fg="blue", bg="white", relief="solid").place(x = 280, y = 100)
Button(f5, text="Save", command=save19, fg="blue", bg="white", relief="solid").place(x = 280, y = 130)
Button(f5, text="Save", command=save20, fg="blue", bg="white", relief="solid").place(x = 280, y = 160)
Button(f5, text="Save", command=save21, fg="blue", bg="white", relief="solid").place(x = 280, y = 190)
Button(f3, text="Create Bar1", command=bac1, fg="blue", bg="white", relief="solid").place(x = 70, y = 220)
Button(f3, text="Create Bar2", command=bac2, fg="blue", bg="white", relief="solid").place(x = 175, y = 220)
Button(f4, text="Create Bar3", command=bac3, fg="blue", bg="white", relief="solid").place(x = 120, y = 220)
Button(f5, text="Create Bar4", command=bac4, fg="blue", bg="white", relief="solid").place(x = 120, y = 220)
Button(f0, text='Custom', command=lambda:raise_frame(f1), fg="blue", relief="solid").place(x = 260, y = 220)
Button(f1, text='Ends:', command=lambda:raise_frame(f2), fg="blue", relief="solid").place(x = 280, y = 190)
Button(f2, text='Bar1', command=lambda:raise_frame(f3), fg="blue", relief="solid").place(x = 5, y = 220)
Button(f3, text='Bar3', command=lambda:raise_frame(f4), fg="blue", relief="solid").place(x = 5, y = 220)
Button(f4, text='Bar4', command=lambda:raise_frame(f5), fg="blue", relief="solid").place(x = 5, y = 220)
Button(f1, text='score', command=lambda:raise_frame(f0), fg="blue", relief="solid").place(x = 280, y = 220)
Button(f2, text='score', command=lambda:raise_frame(f0), fg="blue", relief="solid").place(x = 280, y = 220)
Button(f3, text='score', command=lambda:raise_frame(f0), fg="blue", relief="solid").place(x = 280, y = 220)
Button(f4, text='score', command=lambda:raise_frame(f0), fg="blue", relief="solid").place(x = 280, y = 220)
Button(f5, text='score', command=lambda:raise_frame(f0), fg="blue", relief="solid").place(x = 280, y = 220)

raise_frame(f0)
root.wm_attributes("-topmost", 1)
root.resizable(0, 0)
root.mainloop()
